"""add genres into Venue table

Revision ID: 3881a3217791
Revises: e740d04f2726
Create Date: 2020-07-11 19:43:14.512618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3881a3217791'
down_revision = 'e740d04f2726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
