"""initial migration

Revision ID: e740d04f2726
Revises: da4310cf57d1
Create Date: 2020-07-10 19:05:28.819500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e740d04f2726'
down_revision = 'da4310cf57d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'check_if_migration_works')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('check_if_migration_works', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
